name: rnaseq
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - fastqc=0
  - fastp
  - salmon
  - multiqc=1
  - pigz
  - coreutils=9
  - bash=5
  - parallel
  - curl
  - grep
  - sed
  - gzip
