name: rnaseq-r
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.4
  - r-rmarkdown
  - r-optparse
  - r-readr
  - r-dplyr
  - r-tibble
  - r-ggplot2
  - r-ggrepel
  - r-tidyverse
  - r-enrichr
  - r-writexl
  - r-openxlsx
  - bioconductor-annotationdbi
  - bioconductor-biomart
  - bioconductor-deseq2
  - bioconductor-genomicfeatures
  - bioconductor-rtracklayer
  - bioconductor-txdbmaker
  - bioconductor-tximport
