name: rnaseq-r
channels:
  - conda-forge
dependencies:
  - r-base=4
  - r-rmarkdown=2
  - r-optparse=1
  - bioconductor-tximport=1
  - r-readr=2
  - bioconductor-genomicfeatures=1
  - bioconductor-txdbmaker=1
  - r-dplyr=1
  - r-tibble=3
  - bioconductor-biomart=2
  - r-ggplot2=3
  - r-ggrepel=0
  - r-tidyverse=2
  - bioconductor-deseq2=1
  - r-enrichr=3
  - r-writexl=1
  - r-openxlsx=4
